### ISSUE TITLE
solution for permutation of a palindrome

### ISSUE THREAD

**Issue by zoe-gonzales** [andy-young/Coders-Workshop#48]
Hi, this was from tonight's meeting. It was suggested to create a PR, but I wasn't sure where it should go. Which folder would be best?

```
const isPermPalin = str => {
  let m = new Map();
  for (c of str) {
    if(m.has(c)) {
      m.set(c, m.get(c)+1);
    } else {
      m.set(c, 1);
    }
  }
  let oddCount = 0;
  m.forEach((v,k) => {
    if (v % 2 === 1) {
      oddCount++;
    } 
  });
  return oddCount < 2;
}

console.log(isPermPalin('tactcoa')); // true
console.log(isPermPalin('racecar')); // true
console.log(isPermPalin('aaabbcc')); // true
console.log(isPermPalin('kitten')); // false
```

**Comment by adamvinueza** [comment]
One good way would be to add a `zoegonzales.js` file in the `Coding-Challenges/clockwiseSpiral/solutions` directory in your clone of https://github.com/andy-young/Coders-Workshop

**Comment by zoe-gonzales** [comment]
Sounds good. I put the palindrome solution under collaborators and created a pull request.
